# Generated by Django 4.2.4 on 2023-08-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('create_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('details', models.TextField()),
            ],
        ),
    ]
